package main

import (
	"github.com/ahmedashrafdev/reports/db"
	"github.com/ahmedashrafdev/reports/handler"
	"github.com/ahmedashrafdev/reports/router"
	"github.com/ahmedashrafdev/reports/store"

	_ "github.com/ahmedashrafdev/reports/docs"   // docs is generated by Swag CLI, you have to import it.
	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware
)

// @title Swagger Example API
// @version 1.0
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {
	r := router.New()

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := r.Group("/api")

	d := db.New()
	db.AutoMigrate(d)

	us := store.NewUserStore(d)
	ss := store.NewServerStore(d)
	h := handler.NewHandler(us, ss)
	h.Register(v1)
	r.Logger.Fatal(r.Start("192.168.1.40:8585"))
}
